### ISSUE TITLE
3.5.12 won't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by notfixingit** [ElasticHQ/elasticsearch-HQ#540]
### General information

    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
    ElasticHQ Version:
    Elasticsearch Version: 3.5.12
    Python version (ignore is using docker image): 3.8.5
    Browser Vendor and Version (if applicable):

### Issue Description

Would not start due to Sqlalchemy 1.3.0 requirement from Alembic
After this, error still remained because testresources is not installed
After the above is solved, still had issue connecting with "'Request' object has no attribute 'is_xhr'" error in the output

### Solution

Could not upgrade flask to the latest version as another issue had mentioned because it would look for a function that no longer existed, however I did find a solution to all of the above to get this to work on Ubuntu 20.04

Edit requirements.txt

Change Flask==0.12.4 to 0.12.5
Change SQLAlchemy==1.2.0 to 1.3.0
Add testresources under the # Testing section list

Rerun pip install -r requirements.txt

**Comment by sizeg** [comment]
Thanks, was helpful for me on Debian 10 and python 3.7

**Comment by cu-18bcs1637** [comment]
As of March 22, 2022 after following the above instructions it's working for me. @notfixingit Thanks.
